import React from 'react';
import { Sparkles, Heart } from 'lucide-react';
import { Link } from 'react-router-dom';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-400 py-10 border-t border-slate-800 text-xs mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          <div>
            <div className="flex items-center gap-2 font-black text-white text-lg mb-3">
              <span>AI Based Decision Support System</span>
            </div>
            <p className="text-slate-400 leading-relaxed mb-3">
              V1 Core Clinical Decision Support System: Report Upload, OCR + Biomedical NER, Profile, Medical RAG, Recommendations, Cost/LOS Prediction, and AI Assistant.
            </p>
            <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-slate-800 border border-slate-700 text-slate-300 text-[11px]">
              <Sparkles className="w-3.5 h-3.5 text-sky-400" />
              <span>Powered by Biomedical NER, XGBoost & Semantic RAG</span>
            </div>
          </div>

          <div>
            <h4 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Core Pipeline</h4>
            <ul className="space-y-2">
              <li><Link to="/reports/upload" className="hover:text-white transition-colors">Medical Report Intelligence</Link></li>
              <li><Link to="/profile" className="hover:text-white transition-colors">Clinical Profile</Link></li>
              <li><Link to="/analysis" className="hover:text-white transition-colors">Medical Analysis / RAG</Link></li>
              <li><Link to="/hospitals" className="hover:text-white transition-colors">Personalized Hospital Recommendations</Link></li>
              <li><Link to="/cost" className="hover:text-white transition-colors">Cost & Length of Stay Prediction</Link></li>
              <li><Link to="/assistant" className="hover:text-white transition-colors">AI Healthcare Assistant</Link></li>
              <li><Link to="/travel" className="hover:text-white transition-colors">Medical Travel & Local Connectivity</Link></li>
            </ul>
          </div>

          <div>
            <h4 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Safety Disclaimer</h4>
            <p className="text-slate-400 leading-relaxed">
              AI Based Decision Support System provides AI decision support and medical knowledge retrieval. Content generated by AI should not replace professional clinical diagnosis, treatment, or licensed doctor consultations.
            </p>
          </div>
        </div>

        <div className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4 text-center sm:text-left">
          <p>© 2026 AI Based Decision Support System. V1 Core Edition.</p>
          <div className="flex items-center gap-1 text-slate-400">
            <span>Built with</span>
            <Heart className="w-3.5 h-3.5 text-rose-500 fill-rose-500" />
            <span>for Clinical Decision Support</span>
          </div>
        </div>
      </div>
    </footer>
  );
};
