import React from 'react';
import { Shield, Sparkles, Heart } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-400 py-10 border-t border-slate-800 text-xs mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
          <div>
            <div className="flex items-center gap-2 font-black text-white text-lg mb-3">
              <div className="w-8 h-8 rounded-lg gradient-bg flex items-center justify-center text-white text-sm">12C</div>
              <span>MedicalTravel AI</span>
            </div>
            <p className="text-slate-400 leading-relaxed mb-3">
              AI-Based Medical Travel Decision Support System designed for international and domestic patient travel decision making.
            </p>
            <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-slate-800 border border-slate-700 text-slate-300 text-[11px]">
              <Sparkles className="w-3.5 h-3.5 text-sky-400" />
              <span>Powered by Gemini & Clinical NLP</span>
            </div>
          </div>

          <div>
            <h4 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Core Modules</h4>
            <ul className="space-y-2">
              <li><a href="/reports/upload" className="hover:text-white transition-colors">Medical Report OCR Analyzer</a></li>
              <li><a href="/hospitals" className="hover:text-white transition-colors">Weighted Hospital Finder</a></li>
              <li><a href="/cost" className="hover:text-white transition-colors">XGBoost Cost Estimator</a></li>
              <li><a href="/travel-planner" className="hover:text-white transition-colors">A* Travel Itinerary Planner</a></li>
            </ul>
          </div>

          <div>
            <h4 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Emergency & Safety</h4>
            <ul className="space-y-2">
              <li><a href="/emergency" className="hover:text-red-400 transition-colors">108 Trauma Emergency Panel</a></li>
              <li><a href="/pharmacies" className="hover:text-white transition-colors">24x7 Pharmacy Finder</a></li>
              <li><a href="/translate" className="hover:text-white transition-colors">Medical Prescription Translator</a></li>
              <li><a href="/insurance" className="hover:text-white transition-colors">Cashless Insurance Desk</a></li>
            </ul>
          </div>

          <div>
            <h4 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Safety Disclaimer</h4>
            <p className="text-slate-400 leading-relaxed">
              12C provides AI decision support and medical knowledge retrieval. Content generated by AI should not replace professional medical diagnosis, treatment, or doctor consultations.
            </p>
          </div>
        </div>

        <div className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4 text-center sm:text-left">
          <p>© 2026 12C AI Medical Travel System. Final Year Major Project Edition.</p>
          <div className="flex items-center gap-1 text-slate-400">
            <span>Built with</span>
            <Heart className="w-3.5 h-3.5 text-rose-500 fill-rose-500" />
            <span>for Global Patient Healthcare</span>
          </div>
        </div>
      </div>
    </footer>
  );
};
